export const base = 'white'
export const text = '#434449'
export const danger = '#ef5350'
export const brand = '#F07320'
export const background3 = '#F7F9FA'
export const info = '#ABBFC8'
export const surface = '#EEF3F4'
