name: validate
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  setup:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    runs-on: ${{ matrix.os }}
    env:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_AUTH0_DOMAIN: test
      REACT_APP_AUTH0_CLIENT_ID: test
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: ▶️ Run install
        run: npm i

      - name: ▶️ Run validation
        run: npm run validate
